name: quran_kareem
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
    
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  bloc: ^8.1.0  
  dio: ^5.7.0
  equatable: ^2.0.5
  intl: ^0.20.2
  flutter_bloc: ^8.1.1
  intl_phone_field: ^3.1.0
  get_it: ^7.2.0
  dartz: ^0.10.1
  shimmer: ^3.0.0
  internet_connection_checker: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/quran.json


  fonts:
    - family: ScheherazadeNew
      fonts:
         - asset: assets/fonts/ScheherazadeNew-Bold.ttf
         - asset: assets/fonts/ScheherazadeNew-Medium.ttf
         - asset: assets/fonts/ScheherazadeNew-Regular.ttf
         - asset: assets/fonts/ScheherazadeNew-SemiBold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

